// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcet3vJTMcNCkY0Zm15niZJRuwypqGVM',
    appId: '1:462462033580:web:bde40cf7e75faa7a5c4909',
    messagingSenderId: '462462033580',
    projectId: 'duckingninja',
    authDomain: 'duckingninja.firebaseapp.com',
    storageBucket: 'duckingninja.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4IV1KFFkEhk9cF5qksOKZIJGiinouOkA',
    appId: '1:462462033580:android:9af2d60a68e72df95c4909',
    messagingSenderId: '462462033580',
    projectId: 'duckingninja',
    storageBucket: 'duckingninja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm08hnCswd4_HsZCk6HUHi6CVCH5HvNFA',
    appId: '1:462462033580:ios:391776fba66598b35c4909',
    messagingSenderId: '462462033580',
    projectId: 'duckingninja',
    storageBucket: 'duckingninja.appspot.com',
    iosClientId: '462462033580-1qe1klvk8eepni2kqqi46rtm4n1pmgrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm08hnCswd4_HsZCk6HUHi6CVCH5HvNFA',
    appId: '1:462462033580:ios:391776fba66598b35c4909',
    messagingSenderId: '462462033580',
    projectId: 'duckingninja',
    storageBucket: 'duckingninja.appspot.com',
    iosClientId: '462462033580-1qe1klvk8eepni2kqqi46rtm4n1pmgrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
